SDL_INCLUDE_PATH = r"E:\projects\include\SDL\SDL-1.2.11\include"
SDL_LIB_PATH = r"E:\projects\include\SDL\SDL-1.2.11\lib"
ZLIB_INCLUDE_PATH = r"E:\projects\include\zlib123-dll\include"
ZLIB_LIB_PATH = r"E:\projects\include\zlib123-dll\lib"
ZZIP_INCLUDE_PATH = "E:\projects\include\zziplib-0.10.82-msvc6-lib\include"
ZZIP_LIB_PATH = "E:\projects\include\zziplib-0.10.82-msvc6-lib\lib"
