Import('env')

all_sources = [ 
                "Cpsfile.cpp",
                "Decode.cpp",
                "Icnfile.cpp",
                "Pakfile.cpp",
                "Shpfile.cpp",
                "Wsafile.cpp",
                "Palette.cpp",
              ]


env.StaticLibrary("pakfile", all_sources)


