#ifndef DUNE_COLOURS_H
#define DUNE_COLOURS_H

#define COLOUR_CLEAR 0
#define COLOUR_BLACK 12
#define COLOUR_DARKGREY 13
#define COLOUR_BLUE 11
#define COLOUR_LIGHTBLUE 9
#define COLOUR_LIGHTGREY 14
#define COLOUR_BROWN 95
#define COLOUR_YELLOW 123
#define COLOUR_GREEN 3
#define COLOUR_LIGHTGREEN 4
#define COLOUR_RED 231
#define COLOUR_WHITE 255
#define COLOUR_ORANGE 83

#define COLOUR_DESERTSAND 105
#define COLOUR_SPICE 111
#define COLOUR_THICKSPICE 116
#define COLOUR_MOUNTAIN 47

#define COLOUR_ATREIDES 160


#define COLOUR_ORDOS 176
#define COLOUR_HARKONNEN 144
#define COLOUR_SARDAUKAR 208
#define COLOUR_FREMEN 192
#define COLOUR_MERCENARY 128


#endif // DUNE_COLOURS_H
