Import('env')

SConscript("pakfile/SConscript")

from glob import glob

gui_sources = glob("gui/*.cpp")
structure_sources = glob("structures/*.cpp")
unit_sources = glob("units/*.cpp")
base_sources = glob("*.cpp")

all_sources = gui_sources + structure_sources + unit_sources + base_sources

#all_sources.remove('Menu.cpp')

all_sources = [ "Application.cpp",
                "Settings.cpp",
                "Font.cpp",
                "State.cpp",            
                "DataFile.cpp",

                "TopLevelState.cpp",
                "MenuBase.cpp", 
                "MainMenu.cpp", 
                "IntroState.cpp", 
                "SingleMenu.cpp", 
                "Gfx.cpp",
                "houses.cpp",		# just for colors, hope there will be a better place for these (otpetrik)

                "ResMan.cpp",
              ]

gui_sources = [
                "gui2/Widget.cpp",
                "gui2/Container.cpp",
                "gui2/Button.cpp",
                "gui2/VBox.cpp",

              ]

pak_sources = [ "pakfile/Cpsfile.cpp",
                "pakfile/Decode.cpp",
                "pakfile/Icnfile.cpp",
                "pakfile/Pakfile.cpp",
                "pakfile/Shpfile.cpp",
                "pakfile/Wsafile.cpp",
                "pakfile/Palette.cpp",
              ]

gamelib = env.StaticLibrary("dune_game", all_sources)
guilib  = env.StaticLibrary("dune_gui", gui_sources)
paklib  = env.StaticLibrary("dune_pak", pak_sources)

dunelegacy = env.Program("../dunelegacy", ["main.cpp", gamelib, guilib, paklib] )
pakview = env.Program("../pakview", ["pakview.cpp", gamelib, guilib, paklib] )

Default(dunelegacy)
Default(pakview)


