Import('env')

from glob import glob

gui_sources = glob("gui/*.cpp")
structure_sources = glob("structures/*.cpp")
unit_sources = glob("units/*.cpp")
base_sources = glob("*.cpp")

all_sources = gui_sources + structure_sources + unit_sources + base_sources

#all_sources.remove('Menu.cpp')

all_sources = [ "Application.cpp",
                "Settings.cpp",
                "Font.cpp",
                "State.cpp",            
                "DataFile.cpp",

                "TopLevelState.cpp",
                "MenuBase.cpp", 
                "MainMenu.cpp", 
                "IntroState.cpp", 
                "SingleMenu.cpp", 

                "ResMan.cpp",

                "gui2/Widget.cpp",
                "gui2/Container.cpp",
                "gui2/Button.cpp",
                "gui2/VBox.cpp",

                "pakfile/Cpsfile.cpp",
                "pakfile/Decode.cpp",
                "pakfile/Icnfile.cpp",
                "pakfile/Pakfile.cpp",
                "pakfile/Shpfile.cpp",
                "pakfile/Wsafile.cpp",
                "pakfile/Palette.cpp",

                "main.cpp",
              ]

#all_sources += [env.Object('SDL_rwops_zzip.c')]

env.Program("../dunelegacy", all_sources)


