Import('env')

from glob import glob

gui_sources = glob("gui/*.cpp")
structure_sources = glob("structures/*.cpp")
unit_sources = glob("units/*.cpp")
base_sources = glob("*.cpp")

all_sources = gui_sources + structure_sources + unit_sources + base_sources

#all_sources.remove('Menu.cpp')

all_sources = [ "Application.cpp",
                "Settings.cpp",
                "Font.cpp",
                "State.cpp",            
                "DataCache.cpp",
#                "PictureFactory.cpp",
                "TopLevelState.cpp",
                "MenuBase.cpp", 
                "MainMenu.cpp", 
                "IntroState.cpp", 
                "SingleMenu.cpp",
#				"CampaignMenu.cpp",
                "OptionsMenu.cpp",
				"MentatMenu.cpp",
				"HouseChoiceMenu.cpp",
				"HouseChoiceInfoMenu.cpp",
                "Gfx.cpp",
                "houses.cpp",		# just for colors, hope there will be a better place for these (otpetrik)
                "Strings.cpp",
                "Log.cpp",
                "ConfigFile.cpp",
                "ResMan.cpp",
				"SoundPlayerClass.cpp",
                "pakfile/sound/adl/adl.cpp",
                "pakfile/sound/adl/emuopl.cpp",
                "pakfile/sound/adl/fmopl.c",
				"pakfile/Animation.cpp",
				"pakfile/Stringfile.cpp",
				"pakfile/sound/Vocfile.cpp",
              ]

gui_sources = [
                "gui2/Widget.cpp",
                "gui2/Container.cpp",
                "gui2/Button.cpp",
                "gui2/VBox.cpp",
                "gui2/Label.cpp",

              ]

pak_sources = [ "pakfile/Cpsfile.cpp",
                "pakfile/Decode.cpp",
                "pakfile/Icnfile.cpp",
                "pakfile/Pakfile.cpp",
                "pakfile/Shpfile.cpp",
                "pakfile/Wsafile.cpp",
                "pakfile/Palette.cpp",
              ]

pakview_sources = [  "Application.cpp", 
                     "ConfigFile.cpp",
                     "DataCache.cpp",
                     "Font.cpp",
                     "Gfx.cpp", 
                     "houses.cpp",
                     "Log.cpp",
                     "ResMan.cpp",                     
                     "Settings.cpp",
                     "Strings.cpp",
                     "State.cpp",
                     "TopLevelState.cpp",
					 "SoundPlayerClass.cpp",
					 "pakfile/Vocfile.cpp",
					 "pakfile/IntegratedLibSampleRate/samplerate.c",
					 "pakfile/IntegratedLibSampleRate/src_linear.c",
					 "pakfile/IntegratedLibSampleRate/src_sinc.c",
					 "pakfile/IntegratedLibSampleRate/src_zoh.c"
                  ]

#gamelib = env.StaticLibrary("dune_game", all_sources)
#guilib  = env.StaticLibrary("dune_gui", gui_sources + gamelib)
#paklib  = env.StaticLibrary("dune_pak", pak_sources)

dunelegacy = env.Program("../dunelegacy", ["main.cpp"] + all_sources + gui_sources + pak_sources )
pakview = env.Program("../test", ["pakview.cpp"] + pakview_sources + gui_sources + pak_sources )

Default(dunelegacy)
#Default(pakview)

